# Generated by Django 4.2 on 2025-05-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_cinema_app', '0002_carouselslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
