# Generated by Django 4.2 on 2025-06-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_cinema_app', '0004_rename_phone_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube trailer link', null=True),
        ),
    ]
