# Generated by Django 4.2 on 2025-06-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_cinema_app', '0005_movie_trailer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star_cinema_app.customer')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star_cinema_app.show_table')),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star_cinema_app.seattype')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star_cinema_app.theater')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star_cinema_app.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star_cinema_app.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star_cinema_app.show_table')),
            ],
        ),
    ]
